language: python
python:
  - 3.8
before_install:
  - python --version
# - pip install -U pip
# - pip install -U pytest
  - pip install codecov
install:
  - pip install -r requirements.txt
  - pip install .
script:
  - pytest -q --cov=./ --cov-report=xml # --runslow --doctest-glob="*.rst"
env:
  - CODECOV_TOKEN='25658546-0983-4709-b30b-e83cae772a71'
after_success:
  - codecov
