#!/bin/sh
xmgrace -settype xydy DATASET1 DATASET2 -settype xy FIT.PLT -batch fit12.bat &
xmgrace -settype xydy DATASET3 DATASET4 -settype xy FIT.PLT -batch fit34.bat &
xmgrace -settype xydy DATASET5 DATASET6 -settype xy FIT.PLT -batch fit56.bat &
