
      SUBROUTINE READPAR

      IMPLICIT NONE
      INTEGER SPEED, P, NF
      DOUBLE PRECISION AS0, RF2, RR2
      CHARACTER SCHEME*5, ANSATZ*6
      LOGICAL INCLUDEDVCS, INCLUDEDIS

      COMMON / PARINT /  SPEED, P, NF
      COMMON / PARFLT /  AS0, RF2, RR2
      COMMON / PARCHR /  SCHEME, ANSATZ
      COMMON / PARLOG /  INCLUDEDVCS, INCLUDEDIS

*   Read fixed initialization parameters
      OPEN (UNIT = 61, FILE = "INIT.DAT", STATUS = "OLD")
      READ (61, *) SPEED
      READ (61, *) P
      READ (61, *) NF
      READ (61, *) AS0
      READ (61, *) RF2
      READ (61, *) RR2
      READ (61, *) SCHEME
      READ (61, *) ANSATZ
      READ (61, *) INCLUDEDVCS
      READ (61, *) INCLUDEDIS
      CLOSE (61)

      RETURN
      END
